# Generated by Django 2.2.3 on 2019-08-12 20:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Makale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='başlık')),
                ('content', ckeditor.fields.RichTextField(verbose_name='içerik')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('article_media', models.FileField(blank=True, null=True, upload_to='', verbose_name='Medya Ekle')),
            ],
        ),
    ]
